### ISSUE TITLE
Fan turning on and off every 

### ISSUE THREAD

**Issue by diegogarciaa** [vitorafsr/i8kutils#1]
O cooler do processador fica ligando e desligando a cada 4-5 segundos...

Eu li que o i8k não desativa o controle do cooler via bios... é isso que está acontecendo realmente?

Obrigado

**Comment by vitorafsr** [comment]
O controle do i8k é via SMM. E o i8kmon liga ou desliga o cooler dependendo da temperatura do notebook. Se o seu cooler liga e desliga regularmente a cada 4-5 segundos, talvez o problema seja de outra origem.
