### ISSUE TITLE
Fan Speed not adjusted on Dell Optiplex 7060 miniPC

### ISSUE THREAD

**Issue by Batwam** [vitorafsr/i8kutils#38]
Hello, I noticed recently that my Dell Optiplex 7060 mini-PC tends to run quite hot as the fans don't seem to increase speed even when it gets hot. On inspection, I could see that the CPU was at 90degC and the fan speed were quietly humming at slow speed (1000rpm), doing next to nothing to reduce the temperature when their max speed is 6200rpm. I have `i8kutils` installed and `i8kctl` returns the correct temperature. However, it doesn't seem to get the fan status which is causing it not to apply fan speed changes. 

Output from `i8kctl` (without service tag):

```
/proc/i8k format version:	1.0
BIOS version:			1.2
CPU temperature (Celsius):	68
left fan status:		-1
right fan status:		-1
left fan rpm:			-1
right fan rpm:			891
ac status:			-1
buttons status:			-1
```

Output from `sensors | grep fan`:
```
dell_smm-isa-0000
Adapter: ISA adapter
fan1:         910 RPM  (min =    0 RPM, max = 6100 RPM)
temp1:        +57.0°C  
temp2:        +51.0°C  
temp3:        +51.0°C  
```

I can manually trigger the fan if I run `i8kfan 1 2` (I only have a "right" fan), it does appear to increase the fan speed but the goes directly to max speed (~6200rpm). Speed `(0)` and `(1)` both have the fan runing on low ~1000rpm while `(2)` and `(3)` are also the same which is max speed (~6200rpm) so my fan essentially only has  2 speeds: very low ~1000rpm and very high ~6200rpm. I also played around with the config in `/etc/i8kmon.conf` and changed the speed for speed(1) to be 2000rpm and speed(2) to be 4000rpm but that made no difference.

I have checked white a few posts on this topic and I am not sure why I am getting `-1 -1` for fan status and this cases `i8kmon` not to apply fan speed changes. I however managed to make i8kmon at least start at high temperature by manually changing the following line in i8kmon: https://github.com/vitorafsr/i8kutils/blob/master/i8kmon#L241
from
`if {$status(rstate) == -1 || $right == $status(rstate)} {`
to
`if {$right == $status(rstate)} {`
which makes the code ignore the fact that the status is `-1`

However, this isn't great as it just stays at min speed letting the CPU overheats, and then starts the fan full blast for a few seconds until the temperature goes back to reasonable range, and does that again and again.

To see if I could access various fan speeds, I also tested applying a pwm value directly to the fan pwm1 t
`# echo 191 > /sys/class/hwmon/hwmon3/pwm1`. It does nothing up to a value of 191 and if I apply a value of 192 (or above), the fans does full speed again. Once again, it doesn't look like there is anything between very low and max speed...

For info, I don't have any fan speed settings in the BIOS.

- Has anyone had any luck with fan control on this model including intermediate fan speeds?
- Why does it return a status of `-1` if the fan works? 
- Is there actually only 2 speeds? or is there a way to have a fan speed which depends on the temperature? looking at the output of psensors, it looks like the speed ramps up in ~11 steps.
- Would anyone have any idea bout what might be causing this issue?

PS: I'm running Ubuntu 23.10. I am not actually sure if this is new but I only noticed this recently. To chekc if this could be version specific, I tried Ubuntu 22.04 LTS using LiveUSB as found the same issue with fan status returned as `-1 -1` and i8kmon therefore doing nothing.

**Comment by Batwam** [comment]
For info, I also tried to add `set config(acpi) /usr/bin/true` to my i8kmon.conf as per #28 but that made no difference

**Comment by Batwam** [comment]
other info as I just rebooted to Windows to see how it behaves. I couldn't get any info on the temperature or precise fan speed but could hear the fan run at what felt like medium speed so it's clear that there is more than just on/off control. I'm just not sure if this is an i8kutils issue or is more of a kernel level issue?

**Comment by Wer-Wolf** [comment]
Can you share the output of `acpidump`?
Since the BIOS seems to be the issue, maybe yoi can try an BIOS update?

**Comment by Batwam** [comment]
@Wer-Wolf  thanks for following up. My BIOS is up to date according to Ubuntu's latest firmware update utility
![image](https://github.com/vitorafsr/i8kutils/assets/56710655/c1858118-bc48-4f47-bfdf-71308a25ed76)

I have attached my acpidump: [acipdump.txt](https://github.com/vitorafsr/i8kutils/files/13378502/acipdump.txt)

**Comment by Wer-Wolf** [comment]
Can you also send a copy of the `bmof` files under `/sys/bus/wmi/devices/05901221-D566-11D1-B2F0-00A0C9062910*/`?

**Comment by Wer-Wolf** [comment]
[0001-ACPI-fan-Add-hwmon-support.patch.txt](https://github.com/vitorafsr/i8kutils/files/13383889/0001-ACPI-fan-Add-hwmon-support.patch.txt)
Can you try to apply this patch and check if `sensors` now shows a `acpi_fan` device?

**Comment by Batwam** [comment]
I could have sworn I saw a response with a patch! anyway, see the files from each subfolder here, named according to the subfolder name for clarity:
[bmof_05901221-D566-11D1-B2F0-00A0C9062910.zip](https://github.com/vitorafsr/i8kutils/files/13385597/bmof_05901221-D566-11D1-B2F0-00A0C9062910.zip)

**Comment by Wer-Wolf** [comment]
You right about the response with a patch, sadly this patch had nothing to do with this issue.

**Comment by Batwam** [comment]
ah ah, no worries ;-)

**Comment by Wer-Wolf** [comment]
Can you try and load the kernel driver with the `fan_max` option set to something like 4 and check how writes to `pwm1` act now?
Also, can you tell me what error is returned if you try to read `pwm1` and whats the content inside `fan1_target` for each fan state written?

**Comment by Batwam** [comment]
if I set `pwm1` to 192 or above, and wait a little while, `pwm1`reads 255 and `fan1_target` goes to 6100 (which is pretty much exactly actual speed)
if I set `pwm1` to 191 or below, and wait a little while, both files are empty, actual speed is ~900rpm
![image](https://github.com/vitorafsr/i8kutils/assets/56710655/b68c4278-4a1b-4098-9243-33fd0d1366db)

How would I go about loading the kernel driver with the fan_max option set to 4? Is this something I can set in `/etc/modprobe.d/i8k.conf`?

**Comment by Batwam** [comment]
ok, I have reloaded the modules by adding fan_max=4 to `/etc/modprobe.d/i8k.conf` but it made no difference to i8kctl. 
```/proc/i8k format version:	1.0
BIOS version:			1.2
Dell service tag:		HTL09X2
CPU temperature (Celsius):	53
left fan status:		-1
right fan status:		-1
left fan rpm:			-1
right fan rpm:			913
ac status:			-1
buttons status:			-1
```

My `8k.conf`now contains `options i8k force=1 fan_max=4`. Did I do it right?

**Comment by Batwam** [comment]
Upon inspection, I am now getting max fan speed with a value of 96 or above:
![image](https://github.com/vitorafsr/i8kutils/assets/56710655/1ad03392-fd88-4ba1-b8ea-42fc501900b2)

any value 96 or above returns a `pwm1` value of 128.

`i8kfan -1 1` bring the speed to 900rpm
`i8kfan -1 2` bring the speed to 6100rpm
`i8kfan -1 3` and `i8kfan -1 4`  bring the speed to 1170rpm for some reason. Still a bit random but I prefer than than 900rpm as it provides more cooling so that's a move in the right direction in my books :-)

Edit: same behaviour with `options i8k force=1 fan_max=`3,4,5,6
`fan_max=2` reverts back to default with speed(3) max speed so I'm guess that that's the default value which is incorrect.

**Comment by Batwam** [comment]
I also can't help but notice that there does appear to be steps when the fan speed ramps up to max (0rpm to 6100rpm below) so it does certainly look like the fans is going up step by step, I'm just not sure how to define/access each step...
![image](https://github.com/vitorafsr/i8kutils/assets/56710655/67c6a816-ee1b-4840-adee-222267b50da0)

**Comment by Wer-Wolf** [comment]
Could it be that in fan state 3 the fans are in some sort of automatic mode (the default mode)?
What is the precise error code when reading `fan1_target` with `pwm1` set to 191?

**Comment by Batwam** [comment]
There is no error code, the file is there but it appears to be empty for low `pwm1` values (the threshold min/max is now at 128). It then gets the values `6100` with higher values of `pwm1`:
![image](https://github.com/vitorafsr/i8kutils/assets/56710655/bb01fece-b213-47c4-9b54-59bf40ca0a29)
![image](https://github.com/vitorafsr/i8kutils/assets/56710655/d4da5429-363e-4fd9-bab7-324fb367ec99)

I think that you are onto something with the automatic mode. I just ran stress-ng to heat things up a bit and the fan started to ramp up. I have never been this happy hearing fan noise!
![image](https://github.com/vitorafsr/i8kutils/assets/56710655/9570269f-19f7-4371-a043-e49dede93b05)
so we have:
- state 1: min speed (900rpm)
- state 2: max speed (6100rpm)
- state 3: auto

 I guess I should run `i8kfan -1 3` on startup to leave the system speed 3 constantly? do I even need i8kmon running if I'm going to leave it at level 3 constantly? currently i8kmon doesn't work without the file change I made above to bypass the status check since the fan status returns `-1` anyway.

All in all, we have the follow bugs/issues if I understand correctly:
- status `-1` returned prevents i8kmon from working (although with speed 2 being higher than 3, I'm not sure that would be the right tool for the job). Is this an issue with the `i8k/dell-smm-hwmon` module itself?
- fan_max default value should be 3 or more. Is this an issue with the `i8k/dell-smm-hwmon` module itself?
- assuming the above is fixed, for people wanting to use i8kmon the config should have state (1) at low temp, state (3) mid-temp and state (2) at high temperature which feels a bit odd? Or is there a way to reverse this so state (3) becomes state (2) and we have min/auto/max which seems more logical?

**Comment by Wer-Wolf** [comment]
The first issue has nothing to do with the kernel driver, but is an issue inside `i8kmon`. I belive i fixed it inside my fork.

The second issue can be fixed inside the kernel driver, i can prepare a patch for this. However it might take some time since i am currently upstreaming another patch for the kernel driver.

Regarding the third issue, i would leave the default config as-is, since it works on most machines (yours being an exception).

**Comment by Wer-Wolf** [comment]
If the automatic mode (fan state 3) is not the default mode (which it should), then you should contact Dell and inform them that their BIOS is messed up.

Does the fan speed issue also happen if you blacklist the kernel driver?

**Comment by Wer-Wolf** [comment]
And can you check what happens if you use `cat` instead of `more` when reading `fan1_target`?

**Comment by Batwam** [comment]
Hi, I have blacklisted i8k and the fan now runs as expected and does speed up during stress-ng test (although I don't get the fan speed and composite temperature anymore).

 `cat` instead of `more` when reading `fan1_target` works fine, just an old habit of mine...

**Comment by Wer-Wolf** [comment]
So the fan speed issues do not happen if dell-smm-hwmon (i8k being an alias) is blacklisted during boot?

If that is the case, then this is an serious issue inside the kernel driver. The fan speed should not be affected by the driver unless the user has ordered to do so.

**Comment by Batwam** [comment]
that's correct. as far as I can tell, the `i8k` module appears to disable the `auto` fan mode and leave the fan at min 900rpm speed which leads to the CPU overheating. 

Technically, I don't believe that the module claims to support this particular PC/architecture. Looking at the documentation, it seems focused on laptop so this might be the reason compatibility why mini-PC hasn't been checked. Maybe this module is just not intended to be used on this particular machine but that's still a shame since it does allows to access and control fan speed.

**Comment by Wer-Wolf** [comment]
The driver is designed to be used on any Dell machine which supports this interface.

Does the driver still affect the fan speed after an reboot?

**Comment by Wer-Wolf** [comment]
Please also make sure that i8kmon is disabled before rebooting.

**Comment by Batwam** [comment]
ok, that was another interesting question. So, if I uninstall i8kutils and reboot, the PC properly goes to auto mode so I would be better off without `i8kmon`. Once I install i8kutils, the fan goes to min mode (900 rpm). looking at `hwmon -v`. This seems to be because it is running `/usr/bin/i8kfan 0 0` on startup (could be the default to initialise?). After that it isn't able to set anything else as the temperature goes up due to the the `-1` status value (see `/usr/bin/i8kfan - -` in log)

`i8kmon -v` log during stress-ng test with temperature ramping up from 55degC to 86degC attached:
[i8kmon.log](https://github.com/vitorafsr/i8kutils/files/13399917/hwmon.log)

**Comment by Batwam** [comment]
I have modified by i8kmon again to bypass the status check and defined the .conf as follows:
```
config(0)          = {- 0} -1 60 -1 50
config(1)          = {- 3} 50 70 45 75
config(2)          = {- 3} 60 80 65 85
config(3)          = {- 2} 70 128 75 128
```
it's now working as expected with the fan going to low mode until 50/45deg. I have set it up to run at max if the temp gets over 80degC but I doubt this will ever happen as the temperature seems to stabilise at 65degC / 2500rpm even with all CPUs at 100%. For that reason I haven't been able to check whether stage 2 would kick-in above 85degC but based on the way it's working currently I would expect it to work just fine.

Interestingly also, by allowing i8kmon to change the stage, the i8kmon.log shows the correct state (3) for the fan which shows that the state can be changed and will be recognised but currently the original status `-1` combined with ` if {$status(rstate) == -1 || $right == $status(rstate)} {` is blocking this?

see log with i8kmon `$status(rstate) == -1` bypass and above config: [i8kmon2.log](https://github.com/vitorafsr/i8kutils/files/13400398/i8kmon2.log)

**Comment by Wer-Wolf** [comment]
Ok, then the issue is not inside the driver, but in i8kmon.

I am maintaining a fork of i8kutils which does not suffer from this issue. Maybe you can check it out?

**Comment by Batwam** [comment]
sure I can test it if I manage to compile it, where is it?

**Comment by Wer-Wolf** [comment]
[i8kutils](https://github.com/Wer-Wolf/i8kutils)

**Comment by Batwam** [comment]
I tried your fork and it all seems to work when it comes to running `i8kmon` manually (as long as I update the config temps as above).  btw, it would be nice to get the list of states at the top of `i8kmon -v` as currently, it only displays the modes and temperatures so it's difficult to tell it it loaded an updated confirm if all I do is change the stages. Then, when it runs, it says `switched to state X`. It's not clear if that's because `i8kctl` returns nothing so it doesn't "know"  if the status has been changed or not (similar to previous issue where the change occurs but the status doesn't). if I run `i8kctl` on its own, I get `i8kctl: unable to read fan 1: error reading "file3": invalid argument`

I still require `fan_max=3` in the i8k options list, otherwise I get `[i8kmon] [notice] 'fan 1 does not support fan state 3, using max. fan state 2'` which makes sense since we haven't touched i8k itself.

I'm not convinced the service works as I'm getting the following with `fan_max=3` when I check i8kmon.service status: `Process: 26191 ExecStartPre=/usr/bin/i8kctl mode1 manual (code=exited, status=1/FAILURE)`. This appears to be because this command returns the following: `i8kctl: fan 1 mode controls not found: couldn't open "/sys/class/hwmon/hwmon3/pwm1_enable": no such file or directory`. Is `pwm1_enable` absolutely necessary?

**Comment by Wer-Wolf** [comment]
Ths error over `pwm1_enable` not being found should be ignored by systemd, it is for certain machines who need this.

**Comment by Batwam** [comment]
Ok, I'm not sure this is actually the case as running `systemctl status i8kmon` does return `code=exited, status=1/FAILURE`. Should `i8kctl` on its own work?

**Comment by Wer-Wolf** [comment]
Can you execute `i8kmon -v` manually and send me the output?

**Comment by Batwam** [comment]
thanks for your help once again. see attached. I ran `i8kmon -v` and while doing it, ran a stress test to ramp the temperature up and down: 
[i8kmon.log](https://github.com/vitorafsr/i8kutils/files/13420131/i8kmon.log)

by the way, when the log says `'switched to state 2'`, I assume it should be 'switched to config 2'? Would it be possible to get the actual fan states in the log and whether `i8kmon` considers that what the fans are already in the correct state or not ? the log says `switched` but I'm not sure if it's running the command to change the state constantly or aware that the state has already been changed and applying `- -`.

**Comment by Wer-Wolf** [comment]
It should indeed be called "switched to config 2" in this case. Please note that i8kmon does not attempt to read the fan state, since this function is broken on many machines, so no verification takes place.

**Comment by Wer-Wolf** [comment]
Every time a config switch occurs, the fan states are updated. The special character `-` means that the fan state should not be changed in that state.

If your machine does not require constant fan state changes (some do) to prevent the BIOS from taking over control of the fans, then you can enable the ondemand option inside the config.
This option will only update fan states if the previous config state was different than the current config state.

**Comment by Wer-Wolf** [comment]
Besides this, does the kernel driver load if you omit the `force` option and instead use the `ignore_dmi` option?
If yes, then i can add your machine to the whitelist inside the kernel.

**Comment by Batwam** [comment]
I can confirm that it works as expected with `options i8k ignore_dmi=1 fan_max=3`. What would need to change so `fan_max=3` becomes the default?

also, is it common to have the `auto` mode and have it as a higher stage than `max`? how does it work with other dell machines? I'm just thinking that for new users who want `i8kutils` working out of the box, the default `i8kmon.conf` would work a lot better if `auto` was `stage (2)` and `max` was `stage (3)`. With the current setup, it is quite likely that the fans would go to max speed when the service is started, then stop, then run in max, then stop, and so on... which feels weird.

**Comment by Wer-Wolf** [comment]
Some machines do support this special fan state 3 too, ehile others dont and instead require pwm1_enable being set to 2.

I can submit an kernel patch upstream to whitelist your machine, if you can confirm that no issues (small lags when changing the fan speed, suspend broken, etc) appear when loading the driver.
For the handling of fan state 3 i have to talk with the maintainer on how to handle this.

**Comment by Wer-Wolf** [comment]
For the whitelisting i also need the output of dmidecode.

**Comment by Batwam** [comment]
Ok, I don't think I have even tried suspend as the machine is normally on 24/7 but I'll give it a go.

See `dmidecode` details here:
[dmidecode.log](https://github.com/vitorafsr/i8kutils/files/13438555/dmidecode.log)

Edit: I can confirm no issue after suspend, it all works as expected.

**Comment by Wer-Wolf** [comment]
Here is the patched kernel driver:
[dell-smm-hwmon.zip](https://github.com/vitorafsr/i8kutils/files/13452776/dell-smm-hwmon.zip)

Just build it with `make` and execute (as root) `modprobe -r dell-smm-hwmon` and `insmod dell-smm-hwmon.ko`.

**Comment by Batwam** [comment]
hi, I just tested and I can confirm that it works fine having removed all options from `/etc/modprobe.d/i8k.conf`
The fan info has now moved to `/sys/class/hwmon/hwmon7` (from `hwmon3`)

Interesting read [here](https://lkml.org/lkml/2023/11/22/1533) btw. Is there a way to track the patch to find out in which kernel version it will be included if accepted?

**Comment by Wer-Wolf** [comment]
It will likely land in kernel 6.8, but your machine does not have this WMI interface.

That driver i send you already includes this patches, as i am the same person who send this patch series.

**Comment by Wer-Wolf** [comment]
Something totally unrelated: is a platform device called `MAX34407:00` present on you  machine under `/sys/bus/platform/devices`?

**Comment by Batwam** [comment]
No `MAX34407:00` for my I'm afraid. 
Thanks for your help once again and great seeing that this bug report can hopefully help others in the process

**Comment by Wer-Wolf** [comment]
Ok, i will notify you if you machine is whitelisted upstream.

**Comment by Batwam** [comment]
is the regular i8kutils meant to work not? I'm getting can't open /proc/i8k: No such file or directory error

**Comment by Wer-Wolf** [comment]
Can you send me the output of sensors?

**Comment by Wer-Wolf** [comment]
It could be that, depending on the version of your kernel, the driver i send you does not expose the legacy procfs interface.
This indeed means that the old i8kutils cannot work, but the functionality of the new i8kutils is not impaired.

**Comment by Batwam** [comment]
see relevant part of sensors:
```
dell_smm-isa-0000
Adapter: ISA adapter
fan1:         908 RPM  (min =    0 RPM, max = 6100 RPM)
temp1:        +53.0°C  
temp2:        +48.0°C  
temp3:        +48.0°C  
```

with the regular `i8kutils` running `i8kctl`, I am still getting a status `-1` so it's as per the original issue:
`1.0 1.2 (null) 50 -1 -1 -1 908 -1 -1`

**Comment by Wer-Wolf** [comment]
As i already said, i suspect your BIOS is buggy.
The modified driver should dump a lot debugging information to `dmesg`, could you send me this?

**Comment by Wer-Wolf** [comment]
Just switch thru all fan states and read the stste back again so i can find out what causes the driver to return an error when reading pwm1 under certain conditions.

**Comment by Batwam** [comment]
Ok, I'll do some more digging. I think that after restart, the `/proc/i8k` interface seems to be back.

**Comment by Batwam** [comment]
see result of `sudo dmesg | grep hwmon`: 
[dmesg-hw_smm_hwmon.log](https://github.com/vitorafsr/i8kutils/files/13462787/dmesg-hw_smm_hwmon.log)
Looks like it's continuously sending errors to dmesg. 

at this point, i have simply removed `i8kutils` as I'm happy with the default auto mode. 

For clarity, am I meant to load the patched modules manually on startup? it doesn't seem to be getting loaded automatically.

**Comment by Wer-Wolf** [comment]
The patched modules need to be loaded manually, unless you try to use `dkms` or something similar to integrate them.

Based on the error logs, it seems that the BIOS will return an error if the fan state is less than 2, sadly we cannot do anything to fix this class of bugs, as only Dell can fix their BIOS.

**Comment by Batwam** [comment]
ok, no problem, I can always add this to a crontab on reboot. Is there a way to avoid these errors fill up the log? I'm literally getting 4-5 warning per second now.

**Comment by Wer-Wolf** [comment]
In order to disable the debugging output, edit the Makefile and delete this line:
`CFLAGS_dell-smm-hwmon.o := -DDEBUG`

Then rebuild and reload the module.

**Comment by Batwam** [comment]
Ok, all good now. Thanks again for your help, this was very interesting and I'm glad to hear that this will help improving the kernel module and hopefully help others. Keep going, you are a rock star 👍

**Comment by Batwam** [comment]
Looks like the patch has now [landed in 6.8](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/hwmon/dell-smm-hwmon.c), I'll report back once my distro has been updated and I'm able to check that everything works but this might take a while.

**Comment by Batwam** [comment]
Hi, I just updgraded to kernel 6.8. I am glad to report that the fan speed is variable even without specifying `fan_max=3`. However, I still have to specify `force=1` for the module to load. Is this normal?

**Comment by Wer-Wolf** [comment]
It seems that i forgot to submit the patch whitelisting your machine, sorry xd.

I will send it right away, sorry for the delay.

**Comment by Batwam** [comment]
No problem, thanks for the help 👍

**Comment by Batwam** [comment]
out of curiosity, I noticed at the time the patch was submitted that you had whitelisted the Optiplex 7000 and figured that it might have been because all the Optiplex 70xx might be covered under that. If this doesn't work, does it mean that when you enable this, it will only be for the 7060 specifically and none of the other similar models?
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/hwmon/dell-smm-hwmon.c#n1533

**Comment by Wer-Wolf** [comment]
Yes, i want to wait till more OptiPlex models are proven to be safe before whitelisting the whole OptiPlex series.

**Comment by Batwam** [comment]
hello, I am now running kernel 6.11 and can confirm that I no longer need to specify any option for `i8k` to get variable fan speed control.

**Comment by Wer-Wolf** [comment]
Great :)

**Comment by notfence** [comment]
Hi there! Getting some issues with optiplex 5060. So when i turned on my oc, i8kfans says -1 3 (so i't kinda auto mode), cat /sys/class/hwmon/hwmon1/pwm1 says: 255. In *that* auto mode my fans going aroud 780rpm (max 3300). When I run stress-ng (with --cpu 12) my fan just ignores it, cpu clocks just went from 4.3 to 3.8 and stays. When I trying to set -1 2 (full speed), pwm1 changes to 128. But from now I can't set fan to auto mode, trying set i8kfan to -1 3 gets it to full speed. setting pwm1 to 255 gets it to full speed. I can do i8kfan 0 0, but it stands for silent mode. Only reboot is a choice.
there is my measurements:
only right fan available 
i8kfan 0 0 (silent, 750rpm)
i8kfan 0 1 (medium, 1600rpm)
i8kfan 0 2 (full speed, 3300rpm)
i8kfan 0 3 (full speed again, 3300rpm)
////
with i8kfan set to 0 0:
dell_smm-isa-00de
Adapter: ISA adapter
fan1:         739 RPM  (min =    0 RPM, max = 3300 RPM)
temp1:        +24.0°C
temp2:        +25.0°C
temp3:        +25.0°C
pwm1:             64%
root@pve:~# cat /sys/class/hwmon/hwmon1/pwm1
128

**Comment by Batwam** [comment]
You might want to create a separate issue for this since it's a different machine.

Did you update your `/etc/modprobe.d/i8k.conf` put `options i8k ignore_dmi=1 fan_max=4`, restart/reload, then switch between the modes to see if there is a mode 4 perhaps?

Also, you mentioned several low speeds: 780,750,739. Cold it be thay that that "low" mode is actually variable speed? For info, mine is a microPC and normal speed is around 1,100rpm with cpu around 50degC, 1,600rpm @65degC. Your CPU temps looks surprisingly low which might be why you are getting such low rpm values so you might already be in auto but it's reading the wrong temperature? Do you actually see temperatures changing when running `stress-ng`?

FYI, I used `psensors` to plot speed Vs temps, that was quite useful to see if the speed is fluctuating with temps or not.

**Comment by Wer-Wolf** [comment]
Can you check if kernel 6.19 allows you to switch back to automatic mode by using the `pwmX_enable` sysfs attributes?

Those only work if you do not override `fan_max` using the module parameter.

**Comment by notfence** [comment]
> options i8k ignore_dmi=1 fan_max=4

thanks! now:
i8kfan 0 0 (silent, 730rpm)
i8kfan 0 1 (1600rpm)
i8kfan 0 2 (3300rpm)
i8kfan 0 3 (auto)

**Comment by scratchmex** [comment]
i tried
```
options dell-smm-hwmon ignore_dmi=1 fan_max=4
```

but now `i8kfan 0 3` drives to full rpm, and any intermediate only brings it down to auto. this also changed
```
$ cat /sys/class/thermal/cooling_device11/max_state
4
```

my hw is OptiPlex 3070, more info
```
$ sensors
dell_smm-isa-00de
Adapter: ISA adapter
fan1:         844 RPM
temp1:        +47.0°C
temp2:        +46.0°C
temp3:        +46.0°C
pwm1:             N/A

$ cat /sys/bus/wmi/devices/F1DDEE52-063C-4784-A11E-8A06684B9*/guid
F1DDEE52-063C-4784-A11E-8A06684B9BF4
F1DDEE52-063C-4784-A11E-8A06684B9BF5
F1DDEE52-063C-4784-A11E-8A06684B9BF9
F1DDEE52-063C-4784-A11E-8A06684B9BFA

$ sudo dmesg | grep dell
[    3.540282] dell_smm_hwmon: Probing for legacy SMM handler on unsupported machine
[    3.540285] dell_smm_hwmon: vendor=Dell Inc., model=OptiPlex 3070, version=1.21.0
```

one interesting finding it that if you reload the module, the fans will no longer show; apparently the module only works on boot
```
$ modprobe -r dell-smm-hwmon
$ modprobe dell-smm-hwmon
<fans no longer show in sensors, hwmonX/ lacks pwm>
```
