### ISSUE TITLE
Can't make i8kmon config work after reboot

### ISSUE THREAD

**Issue by slorber** [vitorafsr/i8kutils#4]
Hi,

I'm trying to solve perf problems on my laptop (Dell XPS 13 dev edition) after upgrading Ubuntu 

Here is a related topic: http://askubuntu.com/questions/63588/how-do-i-get-fan-control-working/398635#398635

When running `i8kctl fan -1 2` I can see my fan speed increase, but this is only temporary and it slows down after a while.

I have disabled bios fan control by running `sudo ./smm 30a3` like advised here:
http://askubuntu.com/questions/63588/how-do-i-get-fan-control-working/398635#398635

Now if I run `i8kctl fan -1 2` again, the fan stays at full-speed.

The problem is after reboot, it seems that I have this problem again. Is there a way to remove completely bios fan control so that i8kmon is always in control of fans after rebooting?

**Comment by Thaodan** [comment]
add the smm  call ro the service file see: 
https://github.com/Thaodan/thaopkgs/blob/master/i8kutils/PKGBUILD
https://github.com/Thaodan/thaopkgs/blob/master/i8kutils/i8kmon.service

However the issue with the fn keys still remains.

**Comment by raelgc** [comment]
@Thaodan For me i18kutils persisted after a reboot only if I add a `/etc/i8kmon.conf` file.

**Comment by raelgc** [comment]
In the docs we have:

> Under Debian GNU/Linux it is possible to start the daemon automatically by creating an /etc/default/i8kmon configfile containing the line "set config(daemon) 1"

But in current Ubuntu, the filename must be `/etc/i8kmon.conf`.

**Comment by raelgc** [comment]
Additionally you asked to stop BIOS fan control. So, your file can be like this:

```
# /etc/i8kmon.conf
# Run as daemon, override with --daemon option
set config(daemon) 1

# Automatic fan control, override with --auto option
set config(auto) 1

```

**Comment by vitorafsr** [comment]
Which version of i8kutils are you using?
$ i8kctl -v

**Comment by vitorafsr** [comment]
A first note is that README.i8kutils is outdated; it is being kept as a reference from previous work from other people.

**Comment by vitorafsr** [comment]
File README.i8kutils updated: renamed default configuration filename from "/etc/default/i8kmon" to "/etc/i8kmon.conf".

**Comment by Thaodan** [comment]
@raelgc you misunderstood me. I meant that without calling smm the deamon will not work at all since the BIOS has control over the fans.
So your issue is different. 
As Ubuntu uses systemd too you can use my service file.

**Comment by raelgc** [comment]
@Thaodan I don't any issue, I was trying to help you with 2 issues you mentioned: i8kmon not working after restart (which is expected without additional conf file) and i8kmon taking control on fans over the BIOS.

**Comment by vitorafsr** [comment]
Problem solved executing "smm 30a3" at i8kmon service startup.
